# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - webappforcontainerforbestmoviesbackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://backendbestmoviescontainerregistery.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_de6cabfa04cb4678a9a815808b98113a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4b6fd3780ec1445da1f2f464dc11f2c7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: backendbestmoviescontainerregistery.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_de6cabfa04cb4678a9a815808b98113a }}/backendimage:${{ github.sha }}
        file: ./Backend/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webappforcontainerforbestmoviesbackend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bd150490b4fe412d8b01b4484c15acd1 }}
        images: 'backendbestmoviescontainerregistery.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_de6cabfa04cb4678a9a815808b98113a }}/backendimage:${{ github.sha }}'
